# Generated by Django 5.1.6 on 2025-03-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_customuser_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
