# Generated by Django 5.1.6 on 2025-03-14 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('an', models.IntegerField()),
                ('kilometri', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip_caroserie', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Cabrio', 'Cabrio'), ('Pickup', 'Pickup'), ('Van', 'Van'), ('Break', 'Break')], default='Sedan', max_length=20)),
                ('descriere', models.TextField()),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='masini/')),
                ('putere_motor', models.IntegerField(blank=True, help_text='Puterea motorului în CP', null=True)),
                ('capacitate_motor', models.IntegerField(blank=True, help_text='Capacitatea motorului în cm³', null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_sale',
            },
        ),
    ]
