# Generated by Django 5.1.6 on 2025-03-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='telefon',
        ),
    ]
