# Generated by Django 5.1.6 on 2025-03-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_rename_phone_number_profile_telefon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
